### ISSUE TITLE
Make sure to log failure when attempting to download a new artifact

### ISSUE THREAD

**Issue by ckipp01** [scalameta/coc-metals#142]
**Task**

Currently, if you put in a new version of Metals and we try to fetch it, we just dispose of an error if we get one here.

https://github.com/scalameta/coc-metals/blob/5daf3b472c231a860c7bd0965eb558eaefce670c/src/utils.ts#L19

Let's change this to ensure that whatever happens ends up in the logs and can help debug.

**Comment by ckipp01** [comment]
Related to this, the downloadProgress isn't working right. For example, right now if the download fails, you'll see the following.

```
[coc.nvim] error: Uncaught exception: Error: Coursier exit: 1
    at ChildProcess.<anonymous> (/Users/ckipp/Documents/js-workspace/coc-metals/node_modules/metals-languageclient/lib/downloadProgress.js:24:19)
    at ChildProcess.emit (events.js:215:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```
For some reason this exceptions isn't getting caught, but that doesn't make a ton of sense since the we are providing an `onRejected` function.

**Comment by theof** [comment]
I am getting this exact error (except that coursier exits with -2) when opening a scala file, after following installation instructions for coc-metals.
Is there any workaround so that I can know what is happening and why the download fails ?

> Related to this, the downloadProgress isn't working right. For example, right now if the download fails, you'll see the following.
> 
> ```
> [coc.nvim] error: Uncaught exception: Error: Coursier exit: 1
>     at ChildProcess.<anonymous> (/Users/ckipp/Documents/js-workspace/coc-metals/node_modules/metals-languageclient/lib/downloadProgress.js:24:19)
>     at ChildProcess.emit (events.js:215:7)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Socket.<anonymous> (internal/child_process.js:430:11)
>     at Socket.emit (events.js:210:5)
>     at Pipe.<anonymous> (net.js:659:12)
> ```
> 
> For some reason this exceptions isn't getting caught, but that doesn't make a ton of sense since the we are providing an `onRejected` function.

**Comment by ckipp01** [comment]
Thanks for reporting @theof. There was actually some changes done in the metals-language-server library that both this and the vs code extension use that should actually fix this issue. For example the original issue I listed for me no longer happens as I just tested and got the following, which is expected:

```
[coc.nvim]: Uncaught exception: Coursier exit: 1
Failed to download Metals, make sure you have an internet connection, the Metals version '0.9.6' is cor
rect and the Java Home '/Users/ckipp/.sdkman/candidates/java/current' is valid. You can configure the M
etals version and Java Home in the settings.See https://scalaeta.org/metals/docs/editors/vscode.html#ht
tp-proxy for instructions if you are using an HTTP proxy.
 Open Settings?
[Y]es, (N)o:
```
So it's a bit odd that you're actually getting that as well. I'm going to play around with what you said about the java path being incorrect and seeing what happens.
