### ISSUE TITLE
node 14 is not supported

### ISSUE THREAD

**Issue by svalaskevicius** [scalameta/coc-metals#201]
**Describe the bug**

node v14 build breaks:

```
# yarn install --frozen-lockfile  
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
warning coc-metals@0.8.3: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ npx npm-run-all clean build
yarn run v1.22.4
warning coc-metals@0.8.3: The engine "coc" appears to be invalid.
$ rimraf lib
Done in 0.13s.
yarn run v1.22.4
warning coc-metals@0.8.3: The engine "coc" appears to be invalid.
$ tsc --noEmit && parcel build src/index.ts --out-dir lib/ --target node --no-source-maps
(node:19710) UnhandledPromiseRejectionWarning: Error: Could not locate the bindings file. Tried:
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/build/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/build/Debug/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/build/Release/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/out/Debug/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/Debug/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/out/Release/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/Release/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/build/default/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/compiled/14.1.0/linux/x64/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/lib/binding/node-v83-linux-x64/deasync.node
    at bindings (/home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/deasync/index.js:30:31)
    at Module._compile (/home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (/home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
    at Module._compile (/home/sarunas/.local/share/nvim/plugged/coc-metals/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.92s.
Done in 5.86s.
```

coc-metals - 7b959dc

**Comment by ckipp01** [comment]
Thanks for reporting @svalaskevicius. Could you give me some more information such as coc.nvim version, os, vim/nvim version etc. I went ahead and added Node 14 to the CI to ensure that it's building on all the various os's and everything seems to be green.

**Comment by svalaskevicius** [comment]
Hmm interesting, the yarn command fails even outside vim, so coc or nvim versions should not affect it?

I'm using nixos, and the above command failed when I was using node 14 - after downgrading it - the yarn cmd was OK. I'll check the exact version later when I have a chance.

**Comment by ckipp01** [comment]
> Hmm interesting, the yarn command fails even outside vim, so coc or nvim versions should not affect it?

Actually yea, that's true. 🤔 I'm not fully sure then. Does it also fail if you don't pass in `--frozen-lockfile`? Does it also fail if you try with npm?

**Comment by svalaskevicius** [comment]
Didn't try with npm directly but it did fail without frozen deps too

**Comment by svalaskevicius** [comment]
Also, it did work when node was updated to 14.only failed when this repo was updated afterwards. But then it also failed when I reverted the repo to the original working commit, and only started to work when I downgraded node - from that I could updated the repo again.

I hope this description of the time line makes sense :)

**Comment by ckipp01** [comment]
So I'm unable to get this to fail, and I've tried quite a few different examples with installing from scratch, updating etc with Node 14. At this point I'm open to suggestion of trying something else out. I haven't heard any issues of others having it failed, and it seems to be installing alright with Node 14 on Mac, Linux, and Windows, so I'm not 100% sure what to tell you. Thoughts?

**Comment by svalaskevicius** [comment]
Let's close it for now then :) I've downgraded node and thus don't have the problem anymore, and node 14 is running on ci, so next time I see this one I'll spend more time debugging.

Thanks for your response and for adding it to the ci matrix!

**Comment by ckipp01** [comment]
Of course! Sorry I wasn't able to debug this more. If you do come across it again and get more info, feel free to drop it in here.
