### ISSUE TITLE
Uninstall failed: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by ckipp01** [scalameta/coc-metals#272]
**Task**

When installing metals via `:CocInstall coc-metals` and then later trying to uninstall, you'll often get met with the following error:

```
[coc.nvim] Uninstall failed: Cannot read property 'remove' of undefined
```

Figure out if this is an issue on the coc.nvim side, the coc-metals side, or what. 

**Search terms**

uninstall

**Comment by ckipp01** [comment]
This is the full stack trace:

```
[coc.nvim] Uninstall failed: TypeError: Cannot read property 'remove' of undefined
    at Object.dispose (/Users/ckipp/.config/coc/extensions/node_modules/coc-metals/node_modules/vscode-jsonrpc/lib/events.js:100:41)
    at /Users/ckipp/.config/coc/extensions/node_modules/coc-metals/lib/index.js:18:2778
    at Array.forEach (<anonymous>)
    at r.dispose (/Users/ckipp/.config/coc/extensions/node_modules/coc-metals/lib/index.js:18:2765)
    at Object.disposeAll (/Users/ckipp/.vim/plugged/coc.nvim/lib/util/index.js:47:18)
    at Object.deactivate (/Users/ckipp/.vim/plugged/coc.nvim/lib/extensions.js:814:24)
    at Extensions.deactivate (/Users/ckipp/.vim/plugged/coc.nvim/lib/extensions.js:508:36)
    at Extensions.unloadExtension (/Users/ckipp/.vim/plugged/coc.nvim/lib/extensions.js:898:24)
    at Extensions.uninstallExtension (/Users/ckipp/.vim/plugged/coc.nvim/lib/extensions.js:373:28)
    at /Users/ckipp/.vim/plugged/coc.nvim/lib/plugin.js:357:41
```
If I go to where the issue is actually happening it's here:

```typescript
this.listeners.forEach((d) => d.dispose());
```
However, I'm not fully sure what's going on here or why this is causing problems.
