### ISSUE TITLE
Metals server doesn't start

### ISSUE THREAD

**Issue by jqno** [scalameta/coc-metals#344]
**Question**

I saw on twitter there's a new release of coc-metals, so obviously I wanted to upgrade. After the upgrade though, the Metals server no longer starts for me. I reverted to the previous version, and it still doesn't start. Happens both on Maven and SBT projects.

I'm not sure if this is a Metals issue or a coc-metals issue, so I picked one. I'm happy to move this issue if I picked incorrectly :)

**Installation:**

- Operating system: macOS
- Vim or nvim version: 8.2.1650
- coc.nvim version: commit `08190437e386c3841eaaa0c033ca4ee381d7eb78` -- I think that corresponds to 0.0.79
- coc-metals extension version: commit `eb0e501bd74bda475f463af5b7b645f639cf28ad` -- I think that corresponds to 0.9.5
- Metals version: 0.9.4

**Additional context**

I've tried adding an explicit `metals.javaHome` entry to make sure that the correct JVM is used, but it doesn't seem to help. It's managed with sdkman.io, if that's relevant.

Here's (part of) the content of my `.metals/metals.log` file:

```
2020.11.11 12:39:09 INFO  build tool exit: 0
2020.11.11 12:39:09 INFO  time: ran 'sbt bloopInstall' in 29s
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol local --socket /var/folders/j6/v64w7c6j40l9nlk85ndy9l480000gn/T/bsp-launcher980179579343575154/bsp.socket'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 18436'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> 
error: The launcher failed to establish a bsp connection, aborting...
2020.11.11 12:40:16 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:95)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:122)
	at scala.meta.internal.metals.BloopServers$$anon$1.run(BloopServers.scala:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**Search terms**

**Comment by ckipp01** [comment]
Thanks for the report @jqno! So it's not specifically a coc-metals issue, but let's see if we can get it tackled first. We've seen this in a few places, and it's odd that Bloop is behaving this way.

Do you have Bloop CLI installed? If possible, there is a couple things you can try to help this out.

Firstly, make sure you're on the latest, which is > 1.4.5. With the new version of Metals you want to make sure you're not still on 1.4.4.x You can check this with a `bloop about`. If it's still 1.4.4.x, then do a `bloop exit`, and then open your workspace again with the latest Metals, and it should then start a new Bloop server with the correct version. My first suggestion is to that.

**Comment by jqno** [comment]
Thanks for the quick response! I've updated back to the most recent version of coc-metals (current commit) and done the things you said. According to the metals.log file, it's now on Metals version 0.9.5.

Indeed, I have Bloop CLI 1.4.4 installed locally through Coursier. (Maybe I should remove it? I never run it directly.)

When I do `bloop exit`, I get the following as part of the output in metals.log:

```
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
error: Giving up on waiting for a connection, printing embedded bloop logs:
> No server running at 127.0.0.1:8212, let's fire one...
> Resolving ch.epfl.scala:bloop-frontend_2.12:1.4.5-2-eb51d668...
> Starting bloop server at 127.0.0.1:8212...
> Attempting a connection to the server...
error: Trying a tcp-based connection to the server instead...
Opening a bsp server connection with 'bsp --protocol tcp --port 22705'...
Waiting for the bsp connection to come up...
Waiting for the bsp connection to come up...
```

So it seems like that is using the more recent version of Bloop, but it still ends up in the same stacktrace.

**Comment by ckipp01** [comment]
> Indeed, I have Bloop CLI 1.4.4 installed locally through Coursier. (Maybe I should remove it? I never run it directly.)

If you have it installed vial `cs`, you should be able to do a `cs update bloop` to ensure it's up to date. In the logs this time, did you see it try 5 times?
